### PR TITLE
Update getting-started.md

### PR DESCRIPTION
**Pull request by sguest**
Add factorio-types

My own attempt at writing types for Factorio modding, which actually predates the one listed on the page now.

### CODE REVIEW

**Comment by Zamiell** [comment]
is one of them more complete and/or better maintained?

**Comment by sguest** [comment]
I'm obviously biased since I'm the creator of one, but I do believe mine (factorio-types) is better / more complete.

As far as maintained, I have actions that check for new versions of the Factorio API nightly, auto-build if a newer one exists, and push an updated package to the NPM repo once I approve the workflow.

**Comment by Zamiell** [comment]
@GlassBricks

**Comment by GlassBricks** [comment]
I'm also biased since I'm the creator of the other, but I argue that mine is still much better. Many of the  type features listed on the readme aren't present in factorio-types, typed-factorio includes a few lualib modules, includes the settings stage, and allows multiple stages to exist together.

I am interested in how you got the nightly version check to work, though. I'll likely implement that as well.

**Comment by lolleko** [comment]
I see no issue in having both listed, especially because both are maintained.
I think the it's fine if we let the reader/user decide what to pick.

**Review by lolleko — APPROVED** [review]

**Pull request merged**
